### PR TITLE
🧪 Create a meta-integration test

### PR DESCRIPTION
**Pull request by Hona**
﻿> 1. What triggered this change? (PBI link, Email Subject, conversation + reason, etc)

No PBIs - I just did it in my own personal repo & figured its a good idea for CA template too!

> 2. What was changed?

✏️  Added an integration test that runs on main/PRs that checks that the dotnet new templates work as expected.

> 3. Did you do pair or mob programming?

✏️ 
No

image
Figure: The test creating a dotnet new template & building

### CODE REVIEW

**Comment by danielmackay** [comment]
@Hona - can you update the PR description?

**Comment by Hona** [comment]
@danielmackay Done

**Review by danielmackay — APPROVED** [review]
All looks good.  Can you also include a screenshot that shows this working?

**Comment by Hona** [comment]
@danielmackay also done :)

**Pull request merged**
