### PR TITLE
♻️ Changed startup project in SLN file

### PR DESCRIPTION
**Pull request by jernejk**
When creating a new project, the default was Domain, but this change will make WebAPI as the startup project.

image
**Figure:** Opened the project for the first time after applying the fix.

### CODE REVIEW

**Review by danielmackay — APPROVED** [review]

**Comment by danielmackay** [comment]
@jernejk - can you fix the build error?

**Comment by jernejk** [comment]
Hi @danielmackay, the build error I have is about unable to create a test report because it does not have access to a resource.

It's probably because it's a fork and my fork doesn't have access to the necessary resources.
image

**Comment by danielmackay** [comment]
@jernejk - can you try fixing the error but adding the following permissions to the workflow?

```
permissions:
  id-token: write
  contents: read
  checks: write
 ```
 
 As per: https://github.com/dorny/test-reporter/issues/149#issuecomment-1004820190

**Comment by wicksipedia** [comment]
its most probably because he's running from a fork - `pull_request` triggers only have read only access to the repo.

If you want to continue to use the test-reporter action, you need to add another action that listens for the build/test to complete, download the trx artifacts then add them to the pr.... similar to https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

**Comment by danielmackay** [comment]
@jernejk - why was this closed?  This is something that we'd still like to fix (once we sort the forking issue).

**Comment by jernejk** [comment]
I committed the code to main of my fork as I thought it will be an simple PR but since I have no ability to fix the build and wanted to create a new PR, I just deleted the fork and start over.

I might recreate the PR once we figure out how I can contribute.

**Pull request closed without merging**
